In [1]:
import sys
import os
import pandas as pd
import numpy as np
import torch
import time

sys.path.append(os.path.abspath('../src'))

from sklearn.model_selection import train_test_split
from sklearn.base import clone
from DataLoader import DataLoader
from DataSplitter import DataSplitter
from PipelineBuilder import Pipeline
from CrossValidation import CrossValidation

In [2]:
## Loading data
data_loader = DataLoader(path_train="../data/train.csv", path_eval="../data/validation.csv", path_test="../data/test.csv")
train, validation, test = data_loader.load()
train.shape, validation.shape, test.shape

((29000, 2), (1000, 2), (10000, 2))

In [3]:
## Splitting data
data_splitter = DataSplitter(src_language='english', target_language='portuguese')
X_train, y_train = data_splitter.split(train)
X_val, y_val = data_splitter.split(validation)
X_test, y_test = data_splitter.split(test)

In [4]:
## Reloading model
pipe = Pipeline.load("translatorTransformer1.pt")
pipe

Pipeline(batch_size=128, device='gpu', dropout=0.1, embedding_dim=256,
         epochs=120, lr=0.0005, max_length=30, max_length_decoded=30, n_heads=8,
         num_decoder_layers=4, num_encoder_layers=4,
         tokenizer_method='full words', vocab_size=4000)

In [5]:
preds = pipe.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0].values, 'translation': preds})
preds_df.iloc[500:550, :]

Full Words
7.0843
[ 7. 10. 11. 15.]
time cleaning and encoding test:  3.672912359237671
Training Activated ? False
time predicting test:  198.02525544166565
Time decodig test:  0.06394147872924805

,english,portuguese,translation
500,I'll get my bag.,Pegarei minha bolsa.,Eu vou abrir a minha bolsa .
501,I prayed for God's help.,Orei pela ajuda de Deus.,Eu tenho ajuda .
502,Tom is unenthusiastic.,Tom está sem entusiasmo.,Tom é .
503,Stop wasting money.,Pare de desperdiçar dinheiro.,Pare de gastar dinheiro .
504,"Study hard, and you'll succeed.",Se esforce nos estudo que você terá sucesso.,", e senhores , conseguirá ."
505,Tom looked very concerned.,Tom parecia muito preocupado.,Tom parecia muito preocupado .
506,I guess I'm wrong.,Acho que estou errado.,Eu acho que estou errado .
507,Tom is willing to do that for you.,Tom está disposto a fazer isso por você.,O Tom está disposto a fazer isso por você .
508,You hurt me.,Você me machucou.,Vocês me machucaram .
509,Where is my pencil?,Onde está o meu lápis?,Onde está o meu lápis ?
510,I'm leaving the day after tomorrow.,Vou embora depois de amanhã.,Eu vou ao dia após amanhã .
511,Stop wasting your time.,Pare de desperdiçar seu tempo.,Pare de bater na hora .
512,You'd better do that now.,É melhor você fazer aquilo agora.,É melhor você fazer isso agora .
513,Tom divorced Mary.,O Tom se divorciou da Mary.,Tom culpa Mary .
514,How many different species of spiders are there?,Quantas espécies diferentes de aranhas existem?,Quantas há ?
515,I don't think Tom knows I'm a vegetarian.,Eu acho que Tom não sabe que sou vegetariana.,Eu acho que Tom não sabe que sou vegetariano .
516,Tell Tom. I want him to know it was me.,Conte a Tom. Quero que ele saiba que fui eu.,Diga a Tom que eu quero que ele era .
517,I lost my glasses.,Perdi os meus óculos.,Perdi os meus óculos .
518,Here we are!,Aqui estamos!,Aqui está !
519,Is there anything we can do to help?,Há algo que possamos fazer para ajudar?,Há alguma coisa que possamos fazer ?
520,Tom didn't want to go there alone.,O Tom não queria ir lá sozinho.,Tom não queria ir lá sozinho .
521,Tell me a little bit about your trip.,Conta-me um pouquinho a respeito da tua viagem.,Contem-me um pouquinho sobre a viagem de vocês .
522,The famous poet attempted to commit suicide in...,O famoso poeta tentou cometer suicídio na bibl...,A de o fato em sua .
523,Tom said nothing.,Tom não disse nada.,Tom não disse nada .
524,Can you feel the tension?,Você consegue sentir a tensão?,Você pode me sentir o ?
525,I can barely keep my eyes open.,Eu mal consigo ficar de olhos abertos.,Eu conseguem ficar com os meus olhos .
526,The house is haunted.,A casa é mal-assombrada.,A casa está .
527,What do you want to do tomorrow morning?,O que vocês querem fazer amanhã de manhã?,O que quer fazer amanhã de manhã ?
528,Somebody's made a mistake.,Alguém errou.,A cometeu um erro .
529,This car isn't worth repairing.,Não vale a pena consertar esse carro.,Esse carro não é .
530,Do you think Tom speaks French better than Mary?,Você acha que Tom fala francês melhor do que M...,Você acha que Tom fala francês melhor que Mary ?
531,"No, it's not easy.","Não, isso não é fácil.","Não , é fácil ."
532,Does anybody know that you're here?,Alguém sabe que você está aqui?,Alguém sabe que vocês estão aqui ?
533,How often do you eat cereal for breakfast?,Com que frequência você come cereal no café da...,Com que frequência você toma café da manhã ?
534,Could you read this for me?,Você poderia ler isto para mim?,Será que vocês poderiam ler isso para mim ?
535,It was a blow to us.,Foi um baque para nós.,Foi uma .
536,We're not done.,Nós não terminamos.,Nós não estamos feito .
537,She attempted suicide.,Ela tentou se suicidar.,Ela a doações .
538,"Why don't you come? ""Because I don't want to.""","Por que você não vem? ""Porque eu não quero.""","Por que não quer vir ? "" Por que você não venh..."
539,Why are you sorry for something you haven't done?,Por que se desculpam de algo que vocês não fiz...,Por que vocês estão a de algo que não fizeram ?
540,The room is stuffy.,A sala está abafada.,O quarto está .
541,I've begun doing that.,Já comecei a fazer isso.,Eu mandei fazer isso .
542,I sneeze almost every day.,Eu espirro quase todo dia.,Eu espirro quase todos os dias .
543,That must've happened while Tom and I were in ...,Isso deve ter acontecido enquanto Tom e eu est...,Isso deve ter acontecido e Tom estavam em Bost...
544,Tom killed himself three months ago.,O Tom se suicidou há três meses.,Tom morreu há três meses .
545,You didn't even cry.,Você nem sequer chorou.,Você nem sequer chorou .
546,Humans communicate in a variety of ways.,Os seres humanos se comunicam de várias maneiras.,de uma maneiras em .
547,Keep your hands off my daughter!,Não toque a minha filha!,Tire a sua filha !
548,Tom turned off the faucet.,Tom fechou a torneira.,Tom desligou a torneira .
549,I'll never leave you.,Jamais te deixarei.,Jamais vou deixar você .

In [15]:
phrases = ['I love watching movies',
           "I'm not sure how many people understand what this means.",
           "Don't eat this delicious pizza.",
           "Let's go!",
           "Let's jump into the pool."
          ]
english_df = pd.DataFrame({'english': phrases})
pipe.predict(english_df)

Full Words
6.0
[ 6.   9.  10.  10.8]
time cleaning and encoding test:  0.0043146610260009766
Training Activated ? False
time predicting test:  0.0822610855102539
Time decodig test:  0.0

['Eu adoro assistir ?',
 'Não tenho certeza de pessoas pessoas quem sabes que o Tom gosta .',
 'Não coma comer este camisa .',
 'Vamos voltar !',
 'Vamos na piscina .']

In [7]:
## Reloading model
pipe = Pipeline.load("translatorLSTM1.pt")
pipe

Pipeline(batch_size=128, device='gpu', dropout=0.3, embedding_dim=512,
         epochs=100, hidden_dim=512, lr=0.0005, max_length=30,
         max_length_decoded=30, model_name='LSTM', num_layers=2,
         teacher_forcing=0.5, tokenizer_method='full words')

In [8]:
preds = pipe.predict(X_test)
preds_df = pd.DataFrame({'english': X_test.iloc[:, 0].values, 'portuguese': y_test.iloc[:, 0].values, 'translation': preds})
preds_df.iloc[500:550, :]

Full Words
7.0843
[ 7. 10. 11. 15.]
time cleaning and encoding test:  2.470521926879883
Training Activated ? False
time predicting test:  38.54828882217407
Time decodig test:  0.06145453453063965

,english,portuguese,translation
500,I'll get my bag.,Pegarei minha bolsa.,Eu vou cair a minha sacola .
501,I prayed for God's help.,Orei pela ajuda de Deus.,Eu ajuda para o .
502,Tom is unenthusiastic.,Tom está sem entusiasmo.,Tom é .
503,Stop wasting money.,Pare de desperdiçar dinheiro.,Pare de gastar dinheiro .
504,"Study hard, and you'll succeed.",Se esforce nos estudo que você terá sucesso.,com mel e você seja bem .
505,Tom looked very concerned.,Tom parecia muito preocupado.,Tom parecia estar muito preocupado .
506,I guess I'm wrong.,Acho que estou errado.,Eu acho que estou errado .
507,Tom is willing to do that for you.,Tom está disposto a fazer isso por você.,O Tom está disposto a fazer isso por você .
508,You hurt me.,Você me machucou.,Você me .
509,Where is my pencil?,Onde está o meu lápis?,Onde está meu lápis ?
510,I'm leaving the day after tomorrow.,Vou embora depois de amanhã.,Vou o dia dia amanhã de
511,Stop wasting your time.,Pare de desperdiçar seu tempo.,Pare de gastar seu tempo .
512,You'd better do that now.,É melhor você fazer aquilo agora.,É melhor você fazer isso agora .
513,Tom divorced Mary.,O Tom se divorciou da Mary.,Tom percebeu Mary .
514,How many different species of spiders are there?,Quantas espécies diferentes de aranhas existem?,Quantas de muitas mulheres lá ?
515,I don't think Tom knows I'm a vegetarian.,Eu acho que Tom não sabe que sou vegetariana.,Eu acho que Tom não sabe que sou vegetariano .
516,Tell Tom. I want him to know it was me.,Conte a Tom. Quero que ele saiba que fui eu.,Diga a Tom que eu era o que ele era comigo .
517,I lost my glasses.,Perdi os meus óculos.,Perdi os meus óculos .
518,Here we are!,Aqui estamos!,Fiquem aqui !
519,Is there anything we can do to help?,Há algo que possamos fazer para ajudar?,Há alguma coisa que possamos fazer ajudar ?
520,Tom didn't want to go there alone.,O Tom não queria ir lá sozinho.,Tom não queria ir lá sozinho .
521,Tell me a little bit about your trip.,Conta-me um pouquinho a respeito da tua viagem.,Contem-me um pouco a respeito da viagem dos se...
522,The famous poet attempted to commit suicide in...,O famoso poeta tentou cometer suicídio na bibl...,O conselho dela que tocou partir às atrás da c...
523,Tom said nothing.,Tom não disse nada.,Tom não disse nada .
524,Can you feel the tension?,Você consegue sentir a tensão?,Você pode a ?
525,I can barely keep my eyes open.,Eu mal consigo ficar de olhos abertos.,Eu consigo nos meus filhos nos olhos .
526,The house is haunted.,A casa é mal-assombrada.,A casa está .
527,What do you want to do tomorrow morning?,O que vocês querem fazer amanhã de manhã?,O que quer fazer amanhã de manhã ?
528,Somebody's made a mistake.,Alguém errou.,um erro .
529,This car isn't worth repairing.,Não vale a pena consertar esse carro.,Este carro não tem essas .
530,Do you think Tom speaks French better than Mary?,Você acha que Tom fala francês melhor do que M...,Você acha que o Tom fala francês para o francês ?
531,"No, it's not easy.","Não, isso não é fácil.","Não , não é fácil ."
532,Does anybody know that you're here?,Alguém sabe que você está aqui?,Alguém sabe que vocês estão aqui ?
533,How often do you eat cereal for breakfast?,Com que frequência você come cereal no café da...,Com que frequência você café ao café da manhã ?
534,Could you read this for me?,Você poderia ler isto para mim?,Você poderia explicar isso para mim ?
535,It was a blow to us.,Foi um baque para nós.,Foi uma uma nos .
536,We're not done.,Nós não terminamos.,Não estamos feito .
537,She attempted suicide.,Ela tentou se suicidar.,Ela se .
538,"Why don't you come? ""Because I don't want to.""","Por que você não vem? ""Porque eu não quero.""","Por que não não ? "" Não posso sair para "" . """
539,Why are you sorry for something you haven't done?,Por que se desculpam de algo que vocês não fiz...,Por que vocês estão a de algo que não fizeram ?
540,The room is stuffy.,A sala está abafada.,A sala está .
541,I've begun doing that.,Já comecei a fazer isso.,isso isso .
542,I sneeze almost every day.,Eu espirro quase todo dia.,Eu escrevo quase todos os dias .
543,That must've happened while Tom and I were in ...,Isso deve ter acontecido enquanto Tom e eu est...,Isso deve ter acontecido quando eu Tom em Bost...
544,Tom killed himself three months ago.,O Tom se suicidou há três meses.,Tom desapareceu há três meses .
545,You didn't even cry.,Você nem sequer chorou.,Você nem sequer estava .
546,Humans communicate in a variety of ways.,Os seres humanos se comunicam de várias maneiras.,de uma de uma parte .
547,Keep your hands off my daughter!,Não toque a minha filha!,Tire suas mãos da minha mão !
548,Tom turned off the faucet.,Tom fechou a torneira.,Tom desligou a torneira .
549,I'll never leave you.,Jamais te deixarei.,Nunca vou te deixar .

In [9]:
phrases = ['A young boy is sat on a chair',
           'Soccer players do not understand math',
           'Soccer players are playing soccer',
          ]
english_df = pd.DataFrame({'english': phrases})
pipe.predict(english_df)

Full Words
6.333333333333333
[6.   7.6  7.8  7.96]
time cleaning and encoding test:  0.026250123977661133
Training Activated ? False
time predicting test:  0.04908871650695801
Time decodig test:  0.0

['A garota é jovem em cadeira .',
 'O não consigo entender .',
 'Os futebol estão jogando futebol .']